### PR TITLE
One page layout based on startbootstrap's "freelancer" theme

### PR DESCRIPTION
**Pull request by aecio**
A prettier one page layout for VIDA's web site. @remram44, take a look.

https://github.com/BlackrockDigital/startbootstrap-freelancer

### CODE REVIEW

**Comment by remram44** [comment]
This looks really good 😮

The only thing is that I was using Nikola before (that's why there's a "source" branch) and this is a single static page. But I don't know if we need more pages anyway...

**Comment by remram44** [comment]
Also I'm not sure whether they want to use that -- we have a [wordpress on vida.engineering.nyu.edu](http://vida.engineering.nyu.edu/) (but no one has added any content).

**Comment by remram44** [comment]
(merged on master)

**Comment by aecio** [comment]
I didn't even know that we had this blog!
I did some work on the layout , but the content is still not good tough. Specially, the content when you click on people's photos. :) I will put some basic info taken from the professors's pages and do another PR to fix that.

**Pull request closed without merging**
